spring: 
  application: 
    name: ms-categories
  datasource: 
    url: jdbc:postgresql://172.17.0.2:5432/my_db
    driver-class-name: org.postgresql.Driver
    username: root
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update